import "./globals.css";
import { Footer, Navbar } from "@/components";
import Provider from "./provider";
import { louisGeorgeCafeFont } from "@/utils/fonts";

export const metadata = {
  title: "Deepali Babuta | Experience Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={louisGeorgeCafeFont.className}>
        <Provider>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
